### ISSUE TITLE
[COLR] Colour layout

### ISSUE THREAD

**Issue by simoncozens** [be-fonts/boring-expansion-spec#52]
From discussions with @ctrlcctrlv.

Add a new GPOS lookup type 10:

Type | Name | Description
-- | -- | --
uint16 | posFormat | Format identifier: format = 1
uint16 | layerId | COLR layer ID
uint16 | valueFormat | Defines the types of data in the ValueRecord.
ValueRecord | valueRecord | Defines color adjustment value(s)

Applying this lookup replaces the color of the given layer ID with the color defined in the value record, with xPlacement is interpreted as R, yPlacement is interpreted as G, xAdvance is interpreted as B and yAdvance is interpreted as A. The device offsets are interpreted as variation index offsets as normal.

This allows for dynamic recoloring (as well as showing/hiding) glyph layers based on feature application.

(Ab)using a value record and the variation store gives you the opportunity to vary color records based on variation font axis coordinates for free.

**Comment by ctrlcctrlv** [comment]
You could also use this to allow dynamic layer reordering.

In the CPAL table you would simply define colors that are alpha zero, then in COLR you would repeat the layers. 

Then with these records you could just swap which layer is the alpha zero, achieving effective reordering without needing COLR in GSUB. 

This would be especially useful for fonts like my FRB American Cursive, which right now I have to distribute a version with guidelines and then a version with guidelines and arrows, because there is simply no way for me to turn off the arrows via an OpenType feature, which is incredibly inconvenient and confusing for my users, and is one of the reasons that my distribution of that font consists of 66 files at present.

**Comment by behdad** [comment]
Use COLRv1.

**Comment by rsheeter** [comment]
WRT dynamic recoloring we had imagined a CPAL upgrade adding variation, and perhaps additional color space. Maybe best to file on https://github.com/googlefonts/colr-gradients-spec/issues for consideration for COLR v2?
